### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by SeanChense** [int64ago/AutoBBS#1]
`self.__formhash = re.search(r'formhash=(\w+)', res[3].groups()[0])`
`AttributeError: 'str' object has no attribute 'groups'`

其实是登录成功了，但是报了这个错。
如果把 `.groups()[0]` 干掉发帖会没有权限

**Comment by int64ago** [comment]
其实问题多多，这里判断登录成功就有问题，或者说整个程序中对python的str.find都误用了，应该是 
`if str.find('xxx') != -1`，但是一直困扰我的事并不影响发帖，所以很久没管了，等我有精力在调试吧，你也可以帮我看看什么情况

**Comment by SeanChense** [comment]
我初学 Python 而已

**Comment by SeanChense** [comment]
登录的域名问题
切换到 http://bbs.uestc.edu.cn/
解决

**Comment by int64ago** [comment]
啊啊……福
我在CronWorker.py里写的是bbs.uestc.xxxx
可是AutoBBS.py里的测试代码里没改，怪不得一直可以正常发帖……
感谢
